name: Build Strato APK

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false # Desativamos o download autom√°tico aqui para corrigir o link antes

      - name: Fix Sirit Repository URL
        run: |
          sed -i 's|https://github.com/yuzu-emu/sirit|https://github.com/strato-emu/sirit|g' .gitmodules
          git submodule update --init --recursive

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

      - name: List Files (Para Debug)
        run: find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: strato-debug-apk
          path: "**/build/outputs/apk/**/*.apk" # Busca em qualquer subpasta
